name: Publish
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
    inputs:
      BUMP:
        description: 'Version bump type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  test:
    uses: ./.github/workflows/tests.yml
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
      issues: write

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      statuses: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Release new tag
        run: ./mill --no-server setNextVersion --bump ${{ github.event.inputs.BUMP  }}

      - name: Publish to Maven Central
        run: ./mill --no-server publishSonatypeCentral
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
