name: Publish
on:
  push:
    tags:
      - '**'
  workflow_dispatch:
jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    permissions:
      actions: read
      contents: read
      packages: read
      pull-requests: write
      checks: write
      issues: write
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - run: ./mill publishSonatypeCentral
        env:
          MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
          MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
          MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
          MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
